name: test

on:
  push:
    branches: [ "feature/*" ]

jobs: c6UMXZhoB8CCATeFmoCQUc
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Set google-services.json
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'google-services.json'
        fileDir: './app/src/'
        encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}
    - name: cat
      run: cat app/src/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - name: Remove google-services.json
      run: rm -f app/src/google-services.json
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Detekt run
        run: ./gradlew --parallel --system-prop org.gradle.jvmargs=-Xmx8g detekt
